url = "https://www.gadom.ski/heystac"
stac-path = "stac"

[root]
id = "heystac"
title = "heystac"
description = "A curated geospatial asset discovery experienceâ„¢"
created = "2024-11-08T08:12:00-07:00"
license = "MIT"

[catalogs.microsoft-pc]
href = "https://planetarycomputer.microsoft.com/api/stac/v1"
title = "Microsoft Planetary Computer"

[catalogs.earth-search-aws]
href = "https://earth-search.aws.element84.com/v1"
title = "Earth Search by Element 84"

[catalogs.usgs-landsat]
href = "https://landsatlook.usgs.gov/stac-server"
title = "USGS Landsat"
